import { StyleSheet } from 'react-native';
import { COLORS, DEVICE, GLOBAL_STYLE } from '../../utils/constants';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    backgroundColor: COLORS.white,
    paddingTop: '4%',
    paddingHorizontal: '5%',
  },
  header: {
    height: DEVICE.height * 0.12,
    paddingTop: DEVICE.height * 0.03,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: COLORS.white,
    ...GLOBAL_STYLE.shadow(5),
  },
  mapMarker: {
    backgroundColor: COLORS.primary,
    width: DEVICE.width * 0.1,
    height: DEVICE.width * 0.1,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: '5%',
  },
  markerMapContainer: {
    flexDirection: 'row-reverse',
    width: '30%',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  labelTitle: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  dropDownInput: {
    backgroundColor: '#F3F6F9',
    height: DEVICE.height * 0.06,
    borderRadius: 5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: '3%',
    width: DEVICE.width * 0.9,
  },
  bottomSheetItem: {
    height: DEVICE.height * 0.05,
    backgroundColor: 'white',
    marginVertical: '2%',
    borderRadius: 5,
    width: '90%',
    alignItems: 'center',
    justifyContent: 'center',
    ...GLOBAL_STYLE.shadow(5),
  },
  dropContainer: {
    height: DEVICE.height * 0.1,
    justifyContent: 'space-between',
  },
  infoTitle: {
    backgroundColor: '#2195F313',
    borderRadius: 5,
    paddingHorizontal: '2%',
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: '3%',
    justifyContent: 'space-around',
    width: '100%',
  },
  infoText: { marginLeft: '2%', width: '90%' },
  uploadDoc: {
    borderColor: COLORS.primary,
    borderWidth: 1,
    borderRadius: 5,
    width: '100%',
    flexDirection: 'row',
    paddingVertical: '3%',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: '3%',
  },
  formTitle: { marginVertical: '4%' },
  uploadedImageContainer: {
    borderColor: 'grey',
    borderWidth: 1,
    borderRadius: 5,
    alignSelf: 'center',
  },
  uploadedImage: {
    width: DEVICE.width * 0.3,
    height: DEVICE.width * 0.3,
    borderRadius: 4,
  },
  removeImage: {
    position: 'absolute',
    top: -5,
    right: -5,
    backgroundColor: 'grey',
    justifyContent: 'center',
    alignItems: 'center',
    width: DEVICE.width * 0.06,
    height: DEVICE.width * 0.06,
    borderRadius: 20,
  },
  textAreaContainer: { height: DEVICE.height * 0.18 },
  textArea: {
    borderBottomWidth: 0,
    height: DEVICE.height * 0.14,
  },
  costStatusContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  costContainer: { width: '45%', marginVertical: '3%' },
  costInput: { borderBottomWidth: 0, width: '100%' },
  status: { width: '100%', paddingLeft: '5%' },
  confirmContainer: { flexDirection: 'row', marginVertical: '2%' },
  confirmText: { marginLeft: '2%' },
  keyboardVoiding: { height: DEVICE.height },
});

export default styles;
